// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaCbfQskTIasbYqwnuwm_8woDIaJ75SmY',
    appId: '1:417994147501:web:ca43e3790b1bda30446824',
    messagingSenderId: '417994147501',
    projectId: 'learn-network-pdp',
    authDomain: 'learn-network-pdp.firebaseapp.com',
    storageBucket: 'learn-network-pdp.appspot.com',
    measurementId: 'G-HB2RDGVCXJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6mJs1dA0UsXit2O-_nWkYW85GIohjQdk',
    appId: '1:417994147501:android:ab53f0f51d4abedd446824',
    messagingSenderId: '417994147501',
    projectId: 'learn-network-pdp',
    storageBucket: 'learn-network-pdp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClIeaOwWIowcFPHWJApl1Ns5JJ0by5slw',
    appId: '1:417994147501:ios:8edac5f24b928f26446824',
    messagingSenderId: '417994147501',
    projectId: 'learn-network-pdp',
    storageBucket: 'learn-network-pdp.appspot.com',
    iosClientId: '417994147501-2umo1668jtnnir6urtrs0vurknjcl1fv.apps.googleusercontent.com',
    iosBundleId: 'com.pdp.g5.learnHttp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClIeaOwWIowcFPHWJApl1Ns5JJ0by5slw',
    appId: '1:417994147501:ios:aaf335eac5df99db446824',
    messagingSenderId: '417994147501',
    projectId: 'learn-network-pdp',
    storageBucket: 'learn-network-pdp.appspot.com',
    iosClientId: '417994147501-bhpa3mp1u5jn99fti5mjm6gog9fh6uau.apps.googleusercontent.com',
    iosBundleId: 'com.pdp.g5.learnHttp.RunnerTests',
  );
}
